### PR TITLE
Change SecureRandom from class to object

### LINKED ISSUE #19: SecureRandom should have companion object
The current SecureRandom implementation is designed as an object. It should be implemented as a class with a companion, or (more restrictively and IMHO worse) as an object, because it is ultimately calling static (root-level) functions and properties

### PR DESCRIPTION
**Pull request by IgnacioCarrionN**
Fixes #19

### CODE REVIEW

**Review by soywiz — APPROVED** [review]

**Comment by soywiz** [comment]
LGTM. Thanks!

**Comment by soywiz** [comment]
BTW @IgnacioCarrionN, I saw that there was a companion object, the temporally array might not work on native, so that change looked fine.
Just recalled that it was an open class with a companion object extending the class, so you can use `SecureRandom` directly, but also allowing for subclassing. Can't think right now on an use case for extending `SecureRandom` directly, other than mocking it for testing purposes, or maybe for decorating the class and performing some king of logging.
What do you think on this? Why did you suggested to remove the open class option?

**Comment by penn5** [comment]
I think an open class is always better unless there's a reason not to

**Comment by IgnacioCarrionN** [comment]
I just didn't seen the benefits of being an open class in this case. Given the two options I opted for the less possible of misuse. After @soywiz comment I see the benefits on mocking or logging for example. I can make another pull request doing the change.

**Comment by soywiz** [comment]
Actually, the `SecureRandom` is implementing the `Random` interface, and one could use that interface for delegation, decoration and mocking. But maybe in some places one want to force to receive a `SecureRandom`, and still want to mock it or do stuff.
So yeah, if you can make a PR, that will be appreciated :)

**Pull request merged**
