### PR TITLE
Implement AES/ECB encrypt and decrypt

### PR DESCRIPTION
**Pull request by XuXiangJun**
ECB function:
```kotlin
fun encryptAesEcb(data: ByteArray, key: ByteArray, padding: Padding): ByteArray

fun decryptAesEcb(data: ByteArray, key: ByteArray, padding: Padding): ByteArray
```

And add two CBC fuction:
```kotlin
fun encryptAesCbc(data: ByteArray, key: ByteArray, iv: ByteArray, padding: Padding): ByteArray

fun decryptAesCbc(data: ByteArray, key: ByteArray, iv: ByteArray, padding: Padding): ByteArray
```
Because not only AES 128, but AES 192 and AES 256 are also passed the test. And the iv is requirement for AES/CBC

### CODE REVIEW

**Comment by XuXiangJun** [comment]
Add **ANSIX923Padding** and **ISO10126Padding**

**Comment by soywiz** [comment]
Thanks. It seems that there are conflicts, so I cannot merge it

**Comment by XuXiangJun** [comment]
Perhaps because IDEA auto format the codes, it replace all tabs with blanks. OTL

**Comment by XuXiangJun** [comment]
I'll commit a new PR

**Pull request closed without merging**
